version: '2'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 9000:9000

  redis:
    image: redis:alpine
    restart: always
